test-data: ENC[AES256_GCM,data:5RNSDcS9MeyH2UqsTAg=,iv:yOAO2klupD1SwBhTho0yJcZq5qSVYk5GF3UnzrJvFWo=,tag:blRPLQ+X3PbSX+EnZSWGVQ==,type:str]
users:
    sparks:
        passwd: ENC[AES256_GCM,data:eTK54WiBZVRqt/yCt0i2EGTzvzC0KLrECkWDZqcK3qjFMb5BOWkune9uMP6aPlwrkUpLIFKE/GzXO0lAXGgUhcp7aJ2XOSP9VQ==,iv:gYwQGjIqpDJh4aCfcnzyJ7DdbTYb/ApnKZyewX2lorM=,tag:bkGsoP45T2iwVwyVGhHgKg==,type:str]
networking:
    wireless.conf: ENC[AES256_GCM,data:KzCOEvUEp+GVAjSvK5NfJdkXTf7kZxmXmdmBDhFlr+GnmS+HwK9Gb+G0zL5lRiCEj2Y5xxV+rN7lTeRNRPsvewhcpuLK97pkL9JSEkQFrpR3wxiS1PVTPhYU5i/CKs1eU57j0vKTUIR68q/8VIwSVQnDiQqa3/WcHp4ZNL4ysvYEQB4gzCRkKWD01lEM7JWMOxM8q2xCaZJHEHQdzLWVULl/PnYI+VK7arFx/NF6n54wP97ePAOFzMz8tA2dkY0UznihZhp4ZA==,iv:Ujbwb3FERNxvleNcjs7H8/Iofmu3SEht3lfMY5cX0O0=,tag:Q5SxwzvBueZ09oZHHKL6cw==,type:str]
k3s:
    node-token: ENC[AES256_GCM,data:s6woz0eAqI5RnVI+xG0QY2seiAx8xEo1jeM71Hr9l0z8h1w+0oT0djBgQbE1AzKywAH0md+/ggy9aagXpdKVW8LWyHTBr1KLwfzCB/WJ3UCO4j81Yimc8ZA39ows0kmv405Qy6rtlY9STYzy,iv:hb+XhV7ZNRaOPRWLbq+I7IAETnYbzvbOQe5qVujBJ2w=,tag:xNHbfc77C7K9ccGR/i9/Iw==,type:str]
sops:
    age:
        - recipient: age1jayaggqedpe7djyjpk0a74xxc2vlqzumeah39f548rnkjse76syst7t4pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3U0dQS3BmbEVMTDNUQy80
            WWNIR2NhdU1oeGVzaGd0aDJXNHVDUG5lZHd3CklxVWd6VDhlM3l3QzZ1cDB6b3dD
            QUgvaERSbXFLckJUUkFmTkFOWHl3UkUKLS0tIEoxUEJOL3M1bGlwcHRKOExwdCt5
            VGR3ejRHWUpNbW95WkJiZzY5MHZJbTAK3hAWRMDLNVcRuA0lXHcSi4zHmk6cCdaU
            nI6IfCuQzFSNbHDwDs6Tzx1dpGUpfSglnDrvxR/pOBiLuupMPjo6Vw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p6y752pv3ze0a82lec5lyv5n20xex3ennpscgj8ueu7tecqpfd5s4wqe2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMWsydjlVTmxYck42Z1VF
            RklZQkkvUmtkWllMUVR4NFBIL0VvOXpoVkhRCkF2clpBZmt6NGVYeTJZWnVZL1VK
            anprOHJ0d3hMS0RFbWZiV3VKZDNKM2MKLS0tIHV0Y0tVdXY4Wmd6MWdIR2NVWHll
            K2dzYmt1eXBQLzBPb090L1VSamdCRlUKRAs4EL/iqu903NQzGBLuDLdrkIGnhJnT
            zgecq49LIw6sGoAVA3FpRdkUiKlPW1fXmGyEip8RZf3DERdMzNxnGQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17auaf780ad2m0jm5e348c8fpjeak3795jw8dgnmj6yk02whykdyq5eh9ps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZFFIa1VFc2xwYTFaRWxa
            RjR2K1lKQ2VMMmVsNTJvVGJqNllmSTFJeUVvCmQ2VnRnZHd6OWlVL1lUb3pjdmFU
            Ry9CMFp0TldPaXNrTDBFNDdrakJGTmcKLS0tIHgyWFRjUWFKZ2ZiVzNzUk96bUhW
            MVJsNlFDVk5uR3pVV1ArMkFhUm1CQkUKrhyoqABnjVgdZy0HrSbNLqpQJgE7wcT1
            1rhnPprx3HYWnFN34vG9A7eMHzRfOQN0p7/6Sy0YIbcrGt/2BGODjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16ta5mdc8ywd0654q978a6t44ne02mmmg97xm9nnnpypk2e9ns9rs24lj6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRWVYZnBYUE10Tzd5eHZ5
            cnZSOEtPNStONndoQnBCTDJybGw4TWgwR25nCnQ2UWVaUGhVc056NWEyQVFpVlJI
            SHNIOWlvMzVxdHRHWWh1c0F2UFRSK2cKLS0tIEt5NGljdS9UMzMvbjgxblh1T3pS
            NS9LWnpYRzd6OWNrQUQyZlJNUEhRb1UKP5EAvsmKpI1Yj7xFRulOZ77t5PxqADQe
            E5Zr1JWuSQnn64u9/mezup1gb/Eh+k/qobLtY6pavhLqW8fds2NVSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jnc2r4een0mkr6pqkmd2xp50vd92fmgfukeffxlfgfy34w00l5vqzyz3kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTWloWVlHeHh2c0l5WGoz
            bXBEdGlWcXNOSG9tQ0FvUjVqdWhEK0NuWjNrCmxDcDE4QlRybUpCSzgyMTQ2Q3dH
            SUJvaUVEenNPclRhWUlzQXZFNXRCYzgKLS0tIDU5SDFtV2dDbHRvamtwOElMU29o
            bkZ4U3ZrVnlxMTRCSGlGR0FQNFJjZmMKjzH4Lxh2IjaVke1lR2/nFqPMCEHs6G7G
            CKP0Esg4njGNCPIou10SyUTSEww20Ax8YtozhKhR0CGVcIAmMq2IMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzravexcdmxsgflucyapyadqy3mxa3azha828d3hpxgeva5lccpsuxh25f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISkJoVTlDcmcvUytkT1Bu
            d3FTdStyVkV1ckUvSmp2NTRkd25wZDgxWGwwClRkakRXSVBqNTZDRlUrZmpHQWgr
            d05kb0l5SnVNQ0tENDM1bldCMGpUNTAKLS0tIHVVcnYzYXV6R2FMeGdnRk5WSHRH
            cFhFbWg2SmdVT21VRUlqdlhNZXlod2MK9l5WcU/znM03qXQw258DbMDZNP+1UwsT
            jzsFD9LHYQzuIQMwdDnLKWFgaa3TzBSi30QzKOJ+0lJWCTzImRvtoA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13hh8mw2wh0l7pm2x2tj7wguep6ymv0kns2qfz8n4h5nl9ndtmg4qhnhzzq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRmt4dkVLcVpsbC9obkpB
            UjlwUnNDVXpseEVCSzlFS1FIZkw0S2VVYnlzCks1SGlRTGxUTG13MjF1MlY4Y0VS
            NHVORFJmTkI4WG9jOTBmS0dkMmpONjAKLS0tIDVZOTNTV2NqdlJKbFhpWHFHckY0
            aldRMkVCZGY0SkV6UHhKSHRYbTJGY2cKw8sFtXF+U0P6LqU4yTUn9suLnTksEgdv
            At/zHzm0zMzM6fm3x17EXLpIvlCvwXiQrj8+INVFg7KAVoxevWtnYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age106nfdadmxeg92rylfa5pxzhsv85whqgqkanjuwmpt8zydz880p0qnv2wym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsOEpFaXB4ZGJJeXJXd1k1
            TmZ3MmRkTUpXMEZ2TG5QNUIvZ2ZqT3dwaVgwCjVqTTRCUG5ZekFvQVAyOXBra2pn
            KzAwZS8xSGJ3aU5GVzNwUmdtL0NhU1UKLS0tIFlHUFJEaS91NktnOSt2VUx1UUlN
            bi8xN2ZZbkVORkRhZlZpTUpFRG51ZG8KuwWZOxFcocmaLfFndlhPNJLxXmxeT9PS
            fX6pp7vOFI2JI4klcpxbP+xXfDBSwVs5vFSvVynB7KCkg/Cy1O19Lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T20:16:23Z"
    mac: ENC[AES256_GCM,data:t4Tl5khdaybpdtrme+4edVMai6NBwAPstgrjqWpS9pqBYIPbnX1qwHMRtu5sZ3QJzKRM4s9vIGzw8dErpMvhPE+SPVqjbSbxURd1NbPQ/NFlcclKSDU8ZA7lBoAPqzm3He/Nt6HLCCtSNXw4IsJfQtJ13HsqxKa/Jrsuk+MCwOY=,iv:3GJaqxRJ0iII+SvlpiPyw2Xi9gmUrhB41zK4VlkKEmE=,tag:TZ6h+YUpLOAqPk+Xq1k1cw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
