test-data: ENC[AES256_GCM,data:5RNSDcS9MeyH2UqsTAg=,iv:yOAO2klupD1SwBhTho0yJcZq5qSVYk5GF3UnzrJvFWo=,tag:blRPLQ+X3PbSX+EnZSWGVQ==,type:str]
users:
    sparks:
        passwd: ENC[AES256_GCM,data:eTK54WiBZVRqt/yCt0i2EGTzvzC0KLrECkWDZqcK3qjFMb5BOWkune9uMP6aPlwrkUpLIFKE/GzXO0lAXGgUhcp7aJ2XOSP9VQ==,iv:gYwQGjIqpDJh4aCfcnzyJ7DdbTYb/ApnKZyewX2lorM=,tag:bkGsoP45T2iwVwyVGhHgKg==,type:str]
networking:
    wireless.conf: ENC[AES256_GCM,data:KzCOEvUEp+GVAjSvK5NfJdkXTf7kZxmXmdmBDhFlr+GnmS+HwK9Gb+G0zL5lRiCEj2Y5xxV+rN7lTeRNRPsvewhcpuLK97pkL9JSEkQFrpR3wxiS1PVTPhYU5i/CKs1eU57j0vKTUIR68q/8VIwSVQnDiQqa3/WcHp4ZNL4ysvYEQB4gzCRkKWD01lEM7JWMOxM8q2xCaZJHEHQdzLWVULl/PnYI+VK7arFx/NF6n54wP97ePAOFzMz8tA2dkY0UznihZhp4ZA==,iv:Ujbwb3FERNxvleNcjs7H8/Iofmu3SEht3lfMY5cX0O0=,tag:Q5SxwzvBueZ09oZHHKL6cw==,type:str]
k3s:
    node-token: ENC[AES256_GCM,data:s6woz0eAqI5RnVI+xG0QY2seiAx8xEo1jeM71Hr9l0z8h1w+0oT0djBgQbE1AzKywAH0md+/ggy9aagXpdKVW8LWyHTBr1KLwfzCB/WJ3UCO4j81Yimc8ZA39ows0kmv405Qy6rtlY9STYzy,iv:hb+XhV7ZNRaOPRWLbq+I7IAETnYbzvbOQe5qVujBJ2w=,tag:xNHbfc77C7K9ccGR/i9/Iw==,type:str]
sops:
    age:
        - recipient: age1jayaggqedpe7djyjpk0a74xxc2vlqzumeah39f548rnkjse76syst7t4pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWW1PM2Y2SkVEMG41ZWNQ
            Z0dhbnVWdWh5VVVXOGZENmJoRlNkaGdnaXhRClYwUWY5R2lVOXFjZGJWRGVQVHZD
            bkhETk81YlVtd2JwSXBoK1B0NURhc2sKLS0tIHhRZ2w3WFlqdzBUSmpjVjN1dkFw
            bDJkaHZkbC9sOWtNVTlQK1VVN2tRWlkK1gGgap1aYsNQWh8iyyEwrxTPK92QCpYr
            YKmDDg5V2KFbcsXGDQd2Ps783wioXXaTUBFf7zTELuWu1P7N3BUh5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p6y752pv3ze0a82lec5lyv5n20xex3ennpscgj8ueu7tecqpfd5s4wqe2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpd2k2V1hCR2xXenZ5RG5P
            SUx2NXZObncrYTBUb2xYN2FYR216ZFVlU0N3CjVkckVnOGlubzlrYmpXbXNtS3Ni
            TEg2RXJvS1NyVU13U202UGRsVG1TWlEKLS0tIGZvbUVYUzdBa2JhaXRhRE9qd0FH
            cSt4dkVRY2NaZUxnY0hHSEQrSjVLL2sKxYtSrEOqfeh/B/E+qJN9PJlzrMtwaXJD
            NxAsHxyERXfqZv26Otf+cxghWlOMrryqfg3fNFcgTFpnOOqkI0MG5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17auaf780ad2m0jm5e348c8fpjeak3795jw8dgnmj6yk02whykdyq5eh9ps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzVXJIaEFXVGk1ekZ5bkhx
            YkdXeTZjNVp5ZFNuSEQ4ZU1MYlE5OWhlRUNFCmR3TWFLanFibnFOc2ZFdTByZ0Fv
            dmYvNDB1Vml2cmRXT0cxQ0NBbzgyU1UKLS0tIFA0WmpTUEgyZFh1OEY5d3VpMUNx
            V3ZoeHRVV2RRcWNRODJOZ0ZRaGRHc3cKcZkfKzN5v3iabHL50l8S/bNS6af+bEol
            gTTRojX1B2i8V9QKjfuq2DdIzfS8tZc52ujXjYN7X5alvj1BACxhtQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16ta5mdc8ywd0654q978a6t44ne02mmmg97xm9nnnpypk2e9ns9rs24lj6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUbm1OVk5OakNmYy85TXBH
            VE1DNlpyc0s2OFlvRkJxNEJjcFBFa1REdXkwCm8xYlBoN3NHbFYzbjBmZytrKzQ1
            Y0RTd24vMkwxYmxVOTlRQzZWdnQvdzAKLS0tIFh5RXVyeXMwWGhiYmUwZjVHdHdB
            MnNReTIza2NlQlRQMW1OaFFFM0c2M3cKtjxp49jkb007DIXLYVNQIB1udVT6Pmr0
            h6OEjaBdo/w8nilDF3r6hv4sYOLvSJvFuAcN6vIRttm3DB5YxTP/QA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jnc2r4een0mkr6pqkmd2xp50vd92fmgfukeffxlfgfy34w00l5vqzyz3kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNM2RCMjF2VHY0VjV2OTc3
            dUtXT0x3c0hzUjR5Yk5DOTc0bFg4NTU3Y1MwCjNiNWRsRmVSUGUrS3JHc1pKSldW
            NFhHMzh0bWk4eTNIYndGS0F5eW5JTlUKLS0tIFhkeTRzVlVHWHlybjBLVzVBTm9m
            RmN3VmtGZEdkT1pFczZMTHFraVFpdEkKIxrhXL6IsNyCspJeum4I/FZRzAadduat
            PtECzNfTScyFYOLu+frgSo33cWfMs8e2bYfUPEewt/rnt/aTPFD5aQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzravexcdmxsgflucyapyadqy3mxa3azha828d3hpxgeva5lccpsuxh25f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNzRLODZNUVBxUzdzZXNv
            QVVqTG9NWDRqWTJCRlZFV0tlVlErcmdOVGw0CmQ5SjhHNDlxeURSK2g1dG1hWmIv
            SmRsSStRN3NLc0ZsYjJpY1kreXhkcEEKLS0tIHIzSUtncmhmVzluNDdpWjZJS21Y
            eEtIWEQzMFJDa29jODdrN2NpOHZiQjAK7JZQrwbURv8qd4pg2iv1fsYLa4etjRVe
            go54p8QSwtKykjnPJdb6Wskja5zFKcKnV6ZcwL5c3nnrLiar0FvHdA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age106nfdadmxeg92rylfa5pxzhsv85whqgqkanjuwmpt8zydz880p0qnv2wym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTemsvQllOMGwrNGNpaThz
            VnhxTDNscDZzd0c3NU12d0hCVUN2VUhaY1RZCllqaTd0R2UvVWhzTUE5K2g3dVZq
            QUM3V3JJeFljamprNi9HbDZUQkpobVUKLS0tIHJIeDliU3VzN3A4UHBtQzA2a292
            YllBN2dyUzVGV2FMVFZXMGhwTVliZjAKhpk3vzUr08avxjbikCWMkH1NcZKFeuiG
            nd72kEVRaT7CnEur8NyHHtEWom3ZCUhztGdRNWQFcpSkCUVYvxzY/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-26T20:16:23Z"
    mac: ENC[AES256_GCM,data:t4Tl5khdaybpdtrme+4edVMai6NBwAPstgrjqWpS9pqBYIPbnX1qwHMRtu5sZ3QJzKRM4s9vIGzw8dErpMvhPE+SPVqjbSbxURd1NbPQ/NFlcclKSDU8ZA7lBoAPqzm3He/Nt6HLCCtSNXw4IsJfQtJ13HsqxKa/Jrsuk+MCwOY=,iv:3GJaqxRJ0iII+SvlpiPyw2Xi9gmUrhB41zK4VlkKEmE=,tag:TZ6h+YUpLOAqPk+Xq1k1cw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
