users:
    sparks:
        passwd: ENC[AES256_GCM,data:eTK54WiBZVRqt/yCt0i2EGTzvzC0KLrECkWDZqcK3qjFMb5BOWkune9uMP6aPlwrkUpLIFKE/GzXO0lAXGgUhcp7aJ2XOSP9VQ==,iv:gYwQGjIqpDJh4aCfcnzyJ7DdbTYb/ApnKZyewX2lorM=,tag:bkGsoP45T2iwVwyVGhHgKg==,type:str]
        rclone_pass: ENC[AES256_GCM,data:s2473k4SDpidUBIWE8fYB77Yiy8lv9dr7cbwP/PRSXxWr/vFVrhMoEq4y/Ep1XPX,iv:L6RnwEUt6aFNhi0TYf7vGqL4czhzTjcgNtybEax/1Z4=,tag:bElSjsjLdcaj2+S60CeVnw==,type:str]
networking:
    wireless.conf: ENC[AES256_GCM,data:KzCOEvUEp+GVAjSvK5NfJdkXTf7kZxmXmdmBDhFlr+GnmS+HwK9Gb+G0zL5lRiCEj2Y5xxV+rN7lTeRNRPsvewhcpuLK97pkL9JSEkQFrpR3wxiS1PVTPhYU5i/CKs1eU57j0vKTUIR68q/8VIwSVQnDiQqa3/WcHp4ZNL4ysvYEQB4gzCRkKWD01lEM7JWMOxM8q2xCaZJHEHQdzLWVULl/PnYI+VK7arFx/NF6n54wP97ePAOFzMz8tA2dkY0UznihZhp4ZA==,iv:Ujbwb3FERNxvleNcjs7H8/Iofmu3SEht3lfMY5cX0O0=,tag:Q5SxwzvBueZ09oZHHKL6cw==,type:str]
k3s:
    node-token: ENC[AES256_GCM,data:EdjlEM9GJeZqXTAnmH37uBH9wGh/nUu0zcz1hOklR4stBQsji9oD1pxhK0LEGzGJmXiS6V3J9cwFnnkUUi9HYSRvg4lddUas4aRT63ob/YyT49x2vhBJMVxegxf8GkGhSj+IR/tRAaHmK//2,iv:q1ICs1vApCr4QF3F4LA0vJexIrIe9+511AVT8WuE4Mk=,tag:plJIOhYnWJFc6OGOlpjUmA==,type:str]
comin:
    gh_token: ENC[AES256_GCM,data:0W6nLdKmIYXAr/lR826mRtyfp+Xk+z05vlTrNTRm15oZ1mGOr5pA1A==,iv:gOZc3fnADCg3EgXQj0NjX6da3Rr5xwOF1PLs+Bv9eEg=,tag:2xJJBZobyAH4CbpjaQOCIg==,type:str]
    glab_token: ENC[AES256_GCM,data:xT7FzEaG/eYzqNmRYlUwJx9Wa6GAJIaTLAM8FmLAyrS5OdKQGlhJD8w02YWDMvXX/Ick,iv:2O4mMzfCy3mvLgSEHn/aUQxKMVL9dPfonyFtVdepi0o=,tag:s3txSXwnDnQgJqdlw+ASSQ==,type:str]
sops:
    age:
        - recipient: age1jayaggqedpe7djyjpk0a74xxc2vlqzumeah39f548rnkjse76syst7t4pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwR3VKUm5ITXpTUFgvZ2JH
            Y0F3dzd0aGt1YmJyM3BBSmZCQlQ1YkJ3OVFZCkdGeWViWVFIVGhvb28vR3RhTkFS
            enRTVGZWb0ZFbGppVmhaaEdIV1g5OXMKLS0tIDVGV29wTnVuNlFTMmpWOWcwZS9N
            RTkxQjN4SitaT1VBcGtHSU1SVkl2V0UKc9uSG4yT3Svv23GpdV4Tng0cC/lNbQw1
            3SHU1scLvobe/feMR9fiKzBkRsSjt5PV+K4dPudx5/hfUEWw5bV1MA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p6y752pv3ze0a82lec5lyv5n20xex3ennpscgj8ueu7tecqpfd5s4wqe2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YjZ6eVZybHozWFBlVmpJ
            djB2ZFBYczJleTVWbDRaZkF4V3ZEbmhGMGtFCmlXVHVGM1lDNGZWRkpzWVNHSW1s
            QkJydm4zekphbGJ3NkpBbzFhT0orSmsKLS0tIFFUSDIrdnZYM0grNEFOZlBPSGhu
            bXBXbFhzUWUvTlNKdThkKzhyZHdTdmMK3N6voD3G3EVGlLzHlLXg1igdDcfeLbSr
            +YOWI9/s8CsjKjNawAtIpmGlH4v6msW+pmBpr+dzzo+/LiOc4P56vQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17auaf780ad2m0jm5e348c8fpjeak3795jw8dgnmj6yk02whykdyq5eh9ps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMnRGVUZOSGw3cjZrSzZk
            ODdKY0RNaE9BR2VCekp0Q1pHYVpPTnRsVmk0CkdweWZWaWhNVVZYOEFaSE5lellt
            QkJEMFZwcXVxM3hWV0JYemZOUXZyTFUKLS0tIHR5U0tZVlhMZmFKTkNuY1Vkc3NH
            bU9OUFo2NkpLWFM3d1h5ZGg2VHBzeUUKZuUJZvWgRAAb8XwyhKyNXbU+ibgtvxQ3
            0EWK49zSiCqjfTrHF6Bo2wnhyl/ftFRZP+DZiXAgqsnaNUSEtIa64Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16ta5mdc8ywd0654q978a6t44ne02mmmg97xm9nnnpypk2e9ns9rs24lj6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbGhOc2x4RmhLNU9HUndP
            bkNaMDNBTE9aS2x2YXg2eTRKQzl0MytrQmpNCmNqYkdvSDFPU0ZGdTB4ZFRWbGNJ
            MG80MEliVVdESkRKa0NXN01ha004YjgKLS0tIFh3WStFa05NTDFhaFlRMTdxeDRi
            ZXc2bVZGWGlVYk9mUjdXeEx5R2EyR1EKQGhS1TWY9oB0JvnCrUwzl/MPFNstPrJ+
            dqC18rH2l0nP22WZHclbpaX9JyBeLlbRizdVFt6ScldClbGeZ1arSw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g7r4kxtrqwpxmv5uaj4pkfjx0pedw5yx9gmka4ppy34kqmc8rvuqp9ak6j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTEN3aUhML0FOU2syeUpJ
            ZjJGTm9qUU10NUpVMGV3YjAvSE1iMCsrL1ZzCm5kSjlKY0M0bU9Pdk5ob3pma0Fk
            dE9vT1U3bVd5QzNtb2dKQlNBUG5KWGMKLS0tIE1lcTBtSUxtOTZGYWFUTHJFL3Bz
            V05OVUwyQ3dyRnFPVmJzN2VPTnlmSFEKKOqrbTFj1TmDQmHZl3aAQnLUUwU0bLMF
            eFtC7CZDCUce6l19r+6wyvmp9yM59ZrwXdPM2/JeItsX8IO/2SBCBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jnc2r4een0mkr6pqkmd2xp50vd92fmgfukeffxlfgfy34w00l5vqzyz3kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbzRZaXBDYW5SeVA3UUZM
            OTl5YmZZa0RTOUdoRE15dW5IeXFBOGJrTWdzCmhqYk13ZGFYQUhKS0hPQzBJVFk0
            RE5mcUNVMGJIWGNGek52ZGZyVlN0T3MKLS0tIHN1OTZTOG5FS1AyODV0djExc21X
            aC9xbUVmMXNXZjVRVytNL2xYeG9QZW8KGC2jhzXYypV7BP8nnCzS8I3TVQ+4ryg+
            fM2A+Xjr1pgf7AUGPtauKlX08p5SNc/4xyPCvusPI3WD8kgKw8G2hA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gzravexcdmxsgflucyapyadqy3mxa3azha828d3hpxgeva5lccpsuxh25f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bDY5RCtTNmFOVUg5T1Rn
            WXBuR1FqNGFzd3ROWkdYM0V4R2VFZnU0SnlnCkltS09kQzIvY1oyY3B4bzd0U0Jt
            ZHgwVXI4dTFFekgwTG5Ca0UvYUlLWlEKLS0tIHA5OXFRZ3lPVk5lMmE2aXp4cWhh
            TTRZN0I3Q2NEQ1FEdjlNK2Y4YUZrdnMKO1u3JfYaEVAc5GQ2mFyngOr+tguQKhV+
            CK65bTArZLWC7Ro/V5BYipAy5gy5AfbyqhqWor2MBv66v5iYQHfHRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18xs4rmgwdtpd0f7v89e4qgzu7r9ff0cg9g7duxxnm7gutlculdks52mqvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvcjRVbFdXaDNpeDZ6Z3NI
            L0I0MEgxRmhhVlJTTUxGQ0JGTnRMUHoxLzFBClFDK2VaZlJXQ3YxY2Z2a1NhaC9C
            RXo4bkZxM1U0QVVETnJIOVFiY25kSUEKLS0tIG1ZWVQ1azFlSUUrZG1YR2FzbEZN
            NU1TSDJsRU9yRHRRTUVINFArQTRxNDQKF2DHKhekW89L0PFlVnX+kBQQezPEMP5Y
            XV4TSrITO39VwPS8cqiyqGIX7qHx1fMA4zeERcWGUnyb/XY1w51z6w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mz8x2r8xwhhljmnflvwvk68rge40zvjrtsdm29as4rahl3v7a4cq85m2jw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZGl1cmswOFpmRm5lL0xl
            UStNV0dqWVR0a3lJc3RybWVkVyt6SDY3dHhjCit1Wkh3WWJkUVBGV2JRVkFGM2FF
            eWZjVW9Pci9VMmUzU1RaQzAvVGlxSmMKLS0tIEhXOVBrZ2c1UUk1N05kRlN5SWgw
            SStibU9VaEszUkx6M1h1K3lCWnllMjAKqM8n04cfUqqBJeLsMzddbQ0zZPX6WU20
            do3/aDvZALIqIViGvdQaBn9Ashduz0yic4widE9OQb7rjr6yzwJbNg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1af4f25wyqnxeq2wg05nusmry400slm4w53w7hh6xdw28axhjuczsuhp5xf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIclZHbndMeEQvTTV5YkRo
            bE1Ta0dzcVBud0Q5OStxODlteWdPaTZPQVJjCkM3ZkREeDFtSXpWaG5GV2h3RGdS
            Z0dQRmd2ejgrdU1MTmMwdmlCa2UyRDQKLS0tIHp1V0hZcEJ1YzU0OE9tN1FXeUY1
            aTl6M1UwVlVhbkJhR29MeG5yRUpZd0UKfwFgCbsSRAzXiXeTdTF1sV5JyVNL0O44
            MCcvnna2VJRK+mdcMxviedFKcGx8QJoBqoGRjyrS5fWE4NjfAvjzrQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age106nfdadmxeg92rylfa5pxzhsv85whqgqkanjuwmpt8zydz880p0qnv2wym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTajlYL3NuWll3TjlIOWVt
            STdTbnlMd3l0c05wRlVFZFZlWFc2cXFOMEcwCkdrL2dsdW0xalFOMjZDb20vRW9j
            am1xNDQ4YUlKNVNkZjQ5eVNvclhGYWcKLS0tIEN0WEhLK1Nwb2JTZ0kzLzlhNG1q
            bTlJaWY5R2xLMmQ1K1Uzd3Jxb0QxekkKF812c+M7vTVBCSSkZE8TXktDFAhsZ4Lw
            elYQ9d9njwiD+Eo6+/JGVU8WXmLy/A+3VqQ1pgMelOUZdrzo54tp1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y6ku6mmnguq0utzklrtj9rutv0jz3nfk2jrtje70gte05wfgtyeqtcwukx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLUk1sNHpQQmZZQzgzWXQ4
            NTltYzgzWUhBb091MVFWeGdDSFloaHczUEVBCmdieXYwSmF5S1FOR0tmc3c0bHZ6
            V1BZNXhHUWdzSE1oeGh6Z2ZLSjVKRDQKLS0tIDhzVnBGNWpSaHcrMkgvdkhVbDEw
            ZStjeENRbFcxT0hWdW5jTHlOSWc2REUKESvAmZlCkms7XlUTn7yNzrlhCdHr+uHh
            ruLzGCq1erv3I2okAj2cbo/ogqpMPiy5+vffMJ7CvEI8cInACXfInQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T23:55:38Z"
    mac: ENC[AES256_GCM,data:54UIh2N93KDrSdwCUzUnRV21/PKGR4SOm++OH5YNNK19FcEPXh8qZ5qy9WtnhnSa5EWYJaxDZ7vUh1GMhMTg8dnWbhljQEaaaz2kb5FsqNWNP7WH213yq9mU6Ip3mzPiMvzY8UzHillFzNb8lu0Kz7QkVHW42NecAbsmvJbgPY8=,iv:8TFBaKx+HOGGZJ5xP8XuP9EfBFGMzLc59adYFk/MhfM=,tag:7NZGiSSI7+5vmdCDAfnIyQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
