keys:
  - &admin_sparks age1jayaggqedpe7djyjpk0a74xxc2vlqzumeah39f548rnkjse76syst7t4pl
  - &workstation_alpha age1p6y752pv3ze0a82lec5lyv5n20xex3ennpscgj8ueu7tecqpfd5s4wqe2j
  - &workstation_delta age17auaf780ad2m0jm5e348c8fpjeak3795jw8dgnmj6yk02whykdyq5eh9ps
  - &server_sierra age16ta5mdc8ywd0654q978a6t44ne02mmmg97xm9nnnpypk2e9ns9rs24lj6r
  - &server_romeo age1g7r4kxtrqwpxmv5uaj4pkfjx0pedw5yx9gmka4ppy34kqmc8rvuqp9ak6j
  - &server_whiskey age1jnc2r4een0mkr6pqkmd2xp50vd92fmgfukeffxlfgfy34w00l5vqzyz3kq
  - &server_tango age1gzravexcdmxsgflucyapyadqy3mxa3azha828d3hpxgeva5lccpsuxh25f
  - &server_xray age18xs4rmgwdtpd0f7v89e4qgzu7r9ff0cg9g7duxxnm7gutlculdks52mqvx
  - &server_omega age1mz8x2r8xwhhljmnflvwvk68rge40zvjrtsdm29as4rahl3v7a4cq85m2jw
  - &server_vm_gpu_1 age1af4f25wyqnxeq2wg05nusmry400slm4w53w7hh6xdw28axhjuczsuhp5xf
  - &server_lambda age106nfdadmxeg92rylfa5pxzhsv85whqgqkanjuwmpt8zydz880p0qnv2wym
  - &server_beta age1y6ku6mmnguq0utzklrtj9rutv0jz3nfk2jrtje70gte05wfgtyeqtcwukx

creation_rules:
  - path_regex: config/.*\.sops\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_sparks
          - *workstation_alpha
          - *workstation_delta
          - *server_sierra
          - *server_romeo
          - *server_whiskey
          - *server_tango
          - *server_xray
          - *server_omega
          - *server_vm_gpu_1
          - *server_lambda
          - *server_beta
