users:
    sparks:
        passwd: ENC[AES256_GCM,data:eTK54WiBZVRqt/yCt0i2EGTzvzC0KLrECkWDZqcK3qjFMb5BOWkune9uMP6aPlwrkUpLIFKE/GzXO0lAXGgUhcp7aJ2XOSP9VQ==,iv:gYwQGjIqpDJh4aCfcnzyJ7DdbTYb/ApnKZyewX2lorM=,tag:bkGsoP45T2iwVwyVGhHgKg==,type:str]
        rclone_pass: ENC[AES256_GCM,data:s2473k4SDpidUBIWE8fYB77Yiy8lv9dr7cbwP/PRSXxWr/vFVrhMoEq4y/Ep1XPX,iv:L6RnwEUt6aFNhi0TYf7vGqL4czhzTjcgNtybEax/1Z4=,tag:bElSjsjLdcaj2+S60CeVnw==,type:str]
        ntfy_config: ENC[AES256_GCM,data:CGQeK7hZzEe38YAppnc9yHjCo2e3F3qIN72hADzosBZp3dOWSyT9Vl/3iREfJizXgEEjOk+Tv2AAX/90ggRoK6m98Xh+PayeID2VTCcDI80upL/wctuANAZ5KDkkrdK8ek8OoNwkSXrfTnFJdB1d0Ish9yBUL0ZGB/aQ4kduVGz4jD12Mc6PartQ0g==,iv:eVNUx/M3Vn0ys6LJsWxlCaTjkkeVIiwYEiy6NCJyD7s=,tag:/EtsuRKSDrkqtExxqtY+Zw==,type:str]
networking:
    wireless.conf: ENC[AES256_GCM,data:KzCOEvUEp+GVAjSvK5NfJdkXTf7kZxmXmdmBDhFlr+GnmS+HwK9Gb+G0zL5lRiCEj2Y5xxV+rN7lTeRNRPsvewhcpuLK97pkL9JSEkQFrpR3wxiS1PVTPhYU5i/CKs1eU57j0vKTUIR68q/8VIwSVQnDiQqa3/WcHp4ZNL4ysvYEQB4gzCRkKWD01lEM7JWMOxM8q2xCaZJHEHQdzLWVULl/PnYI+VK7arFx/NF6n54wP97ePAOFzMz8tA2dkY0UznihZhp4ZA==,iv:Ujbwb3FERNxvleNcjs7H8/Iofmu3SEht3lfMY5cX0O0=,tag:Q5SxwzvBueZ09oZHHKL6cw==,type:str]
k3s:
    node-token: ENC[AES256_GCM,data:EdjlEM9GJeZqXTAnmH37uBH9wGh/nUu0zcz1hOklR4stBQsji9oD1pxhK0LEGzGJmXiS6V3J9cwFnnkUUi9HYSRvg4lddUas4aRT63ob/YyT49x2vhBJMVxegxf8GkGhSj+IR/tRAaHmK//2,iv:q1ICs1vApCr4QF3F4LA0vJexIrIe9+511AVT8WuE4Mk=,tag:plJIOhYnWJFc6OGOlpjUmA==,type:str]
comin:
    gh_token: ENC[AES256_GCM,data:0W6nLdKmIYXAr/lR826mRtyfp+Xk+z05vlTrNTRm15oZ1mGOr5pA1A==,iv:gOZc3fnADCg3EgXQj0NjX6da3Rr5xwOF1PLs+Bv9eEg=,tag:2xJJBZobyAH4CbpjaQOCIg==,type:str]
    glab_token: ENC[AES256_GCM,data:xT7FzEaG/eYzqNmRYlUwJx9Wa6GAJIaTLAM8FmLAyrS5OdKQGlhJD8w02YWDMvXX/Ick,iv:2O4mMzfCy3mvLgSEHn/aUQxKMVL9dPfonyFtVdepi0o=,tag:s3txSXwnDnQgJqdlw+ASSQ==,type:str]
sops:
    age:
        - recipient: age1jayaggqedpe7djyjpk0a74xxc2vlqzumeah39f548rnkjse76syst7t4pl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTThBdDRwYjFra1MvcGNx
            Um0wRTNDVkoxdlpzUjJEUVBkWVFlRFJmeUJjClhxS3JLTXFxV0FTK1VqUzlkdFRZ
            M0kxenMwK24xZVlqRnp6S3pYMEUvQlEKLS0tIFJISU1qQWlyZXhScEcvUWMxTkEz
            UGJmN0tUVGlsUld5SUpUdThzSm5YL2MKHH7PQTkUGFNFyy0q5cwLZXG5cbDzaNKh
            rpoWsUWMYt3tVMBiUktcRcodUxwIwoJd1l7ve4Du7ZePr1gD12tAhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1p6y752pv3ze0a82lec5lyv5n20xex3ennpscgj8ueu7tecqpfd5s4wqe2j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZQnM0NFpHWW83aG1sc3Q1
            bjM4RmpON05oeW5PVDI2WDl2RmpIRTJleVY0CmhYT1VXMTBsQzFxNGgrTTJOYzVm
            aFBvZ1QwQWMxVVB1UVBTQzh5WkFRcmsKLS0tIHd4TGpneGs4anNNOXJzVGJuNlRP
            bXUxTzZQSU5zUnlqamY0a1oyV09pQlkKW9O9GUS2aVhHfX1gxJT4aCcLklMa7d2O
            N/qqo7hqF5kB5sFL8+yax9Z1aFxQHAa2oP1Oz92sS/yH1meH0/EGZw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17auaf780ad2m0jm5e348c8fpjeak3795jw8dgnmj6yk02whykdyq5eh9ps
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWWhLTmE3VmlpN2pKQTZh
            Q05OMC9SR0xNVjhuT0d4NTBEV2dmQTBVUjJNCnVCUUs3WnhmcW1Pakp3NlZjWTFN
            cTZ2VlVoUHp4eGZqZ2daWUpNOWJjVTgKLS0tIEhhcXV4TmdUb3VmU01Hb3Vjc2p4
            amcvekxtZm1LTzhOdXRtejRQbWljTVUKC3FwCzyhLYAMSgZ1tvfArQMxBq0ImZTH
            XKT5c6+W4d8lCjBvf8Lu1g2UjdBT9/g2tacBCMAHvMTJrinqqblG8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age16ta5mdc8ywd0654q978a6t44ne02mmmg97xm9nnnpypk2e9ns9rs24lj6r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVmdNWGZ6eFgvNjRVVjlD
            NTd0ZjN2NXVSYTR0eGJPUXB2SGR2MzVnQW1ZCkRxckZDeldZczFjRm96cHVJd0w3
            YW1VU013SjJZdTl5RnQ0eEk5dDZ5VFEKLS0tIHdRdUhMaHVZdE9yOXFMVjdkb3VU
            dUlmOE5xZmRYVHlWeHZHS2o4UXdCSWsK0zqbWVWuMaHcjpKv4gg1NKXk4bjq3Pq+
            2kw1mUUwOMBm7hP9peLpQI8Sm2EwucOd7rkSGRoVkpz4uRG9TWWPEA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g7r4kxtrqwpxmv5uaj4pkfjx0pedw5yx9gmka4ppy34kqmc8rvuqp9ak6j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd3U5QlY0YlowWWI0N1JK
            bmx6SlVZNExjRlJQcVdGaDZFVlRCeDFYazMwCmxMMEFCVWJSUTN2ZTJ2MmU2UWt0
            VXdoaGdYSzNTQzhmZTUveUJlQzRZQzQKLS0tIDhoNFJyNEpEK0Y4MkpjeWt2emxV
            L0RSOUdvMUxUbHhhckxxSHZaQmg1WFEK8cHdsxWwGgWw4KdK+1gRTiDfAqC9t7lv
            D3Zfsd/RgAmLq2++kNCKFMwqTm42udowyal5YWZBCwFey5tN5mxtpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1jnc2r4een0mkr6pqkmd2xp50vd92fmgfukeffxlfgfy34w00l5vqzyz3kq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYaW1NeUphOWt6UWdqd2t3
            SXgyYnFrbHFoQmJpM0l1WVAvdVZvUTJFMlVNClBFOG1Eb2Z2ZGp6Wk9lZUF2emc3
            MW1SUEd5UFc0WnY2ZnFScm1mbFdkdTAKLS0tIGxNQTNlKzFoRXdqRXRZdVN6Wnox
            aWFTbjh4amlOVEtlNnFGeS9QbmN6U0kKCIpbGQG6OzxLN+FEwxL13DztitSVA7UJ
            g2mEZb7sTjCb5X+7HGU4hYNDXsIplFB/MKjKtMKEWotsKuByTtOcnQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1e937w3zautvc5yev0zlwnlut35jdrfruz87ml68zd98s0tcghetq5v5u9n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWXRUbVd6M0xvUGl3Qyty
            SVVXYzkxdjN1eWZxaGEzZGVxblVCRTl1M2p3CjlwOVhsb3pvTXVMenRrRUNUOUl3
            TC8zTlBoRDlOS3RLNCtaeGtDM2RoZUEKLS0tIDJ1NzhVQkhnVE1xN3JzZldYZjc5
            ZU1sTnl6cGhUblJzV0lSeHVnMktkbHcKMQukJeUlp8/272qz446ansKk7Lt+orAW
            V7lWVAwyp/sIpIgQOfyTFm3cGvcCD3OCNDN5PpPIre4KhjXrPOMEVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18xs4rmgwdtpd0f7v89e4qgzu7r9ff0cg9g7duxxnm7gutlculdks52mqvx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLbUpRT3JJNEhXMnNKdDZC
            V2g1WmNFdi9EcTdZZUhKNkM4dzM0cXhqeUVFClhVcXhLcUE5REJPYUkrZDBpajd2
            SFZPaXJKRkRDNUpYS2VmRzZyWkdBdk0KLS0tIE5JZWdEbnhhNVYyQnpnM2VSSjk0
            TVVlNDJSVkx3UmhXSExTRkJBd21QZkEK5pstnEqMe0g2P2v82gax4A6hbv4HyVWX
            sBMDPl+HSlqTu9TMidksMz55wja2PLVEcWoEs0rd+TRVkcT/4llOlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1mz8x2r8xwhhljmnflvwvk68rge40zvjrtsdm29as4rahl3v7a4cq85m2jw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsK2J2WnFvWjFtVkc4d1RF
            a3JBZVBkcHFBcDBKN2ZJdmVFczk1NERTRG1zCjRXQVFId05XNjQzT1FUcjNRdk1n
            WkFiS1NnRnpobzN5OWZEdkRzdWVSY0kKLS0tIHpKUlJrNFlTSzJhclR4NEZlckI3
            a3BaZy9zNEJ5WmUybzZNRUpBS2s2cVEKMtvAdfOaSL/Pr6TXr9X8LTMdL9e1hJxa
            7g9p+/xUB2jD34k+Mqg9o0PVxu7khYkieZMBJYJoazxEf/Wg2Q+YqQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1af4f25wyqnxeq2wg05nusmry400slm4w53w7hh6xdw28axhjuczsuhp5xf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqVUNtRGtCUCtSSnJETENw
            TGZQLzkyNEhsNHY3S283bjNKZEdiMXNKc0FzCkh4NDQ0MVpSNkhJZHZDMXNxQWN5
            VHp5RDF0M001MWQ5L0VjWXNudXdWRW8KLS0tIDYyNWFLZ3c0bHhKZVp3eEZvRDVv
            R3RBQUF0c0VWOFZrZk1JcTFzdXlEVzAK8lCW4CpHFY27Xe+dFEgLTwWLx9zZJDaV
            xqHBrL6Lf56bcyYvq69NNDpGhWjFDoC1IRk4x3kFy0kgDwqUpG61xw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age106nfdadmxeg92rylfa5pxzhsv85whqgqkanjuwmpt8zydz880p0qnv2wym
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaWk0RndRcVc4SStHWkFo
            RzgwMjFGRjRlS0U4N0t5R05qTnJia0xheFVVCm5KU2p6RzlsU2o0NkZtZFhZZ3dv
            cElHZ09sMGlJOVdpUXd1UkxuNkdEVE0KLS0tIDc4RUpXV0x3RjUxbHRiMzdaVkFG
            R2JwNGVwUWpzSlpZcnpodnlhdTRaZTAKKh6fcES/JA2ZlddjfX80zuNdHqUUf3Fd
            VH6td7/ooWnssWcop3SjtlmbaKDKTULzh6seRHuOtDyR6kL6VOBAxw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1gxvmq7jj9f28pe6td68c2glmzxa9ja8g3pygd4xdm0zgnvdjlvgsgdawth
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGeW40RGEwWityaTdYVDVr
            ays0am15QUZDamhFR0cvOEdNbTYvcjZGbTI0ClBsNDkySEtMVVBralBkM2lEci9I
            b3A5cEdFYkdSUlZreGQ2SGk2NTY0YjAKLS0tIHplRm1RVXoxbWkxaDFiNm5XVzh2
            N2I4c1U2WXYzVE41U1FIblJoUThFb0UKoLx5RaPMKBNhQ5tEeBKEW72QKCueASt7
            hhD6t15f5KwJslAIolA2iMlAJ++g02cj+If/9tR4MZOaRHO+Ja5+OQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-10T20:01:31Z"
    mac: ENC[AES256_GCM,data:qnE22P4t380tvPdA+wFvH3MtzFCv1eJ/9ElXLY4PbXOoVUXYX5EFczFlH8nnL8Y5yWGYftTgNbZWvgwEpRv/XV6F83zDf+8pQ8FkWxOpRNb1D7j6673GBwgnkzlYSWWY1+ehC7V3G9wxRxDhUEupDV0CcENiybZ8V8Me5Wn18dM=,iv:G00zaF5jSHTtJvgn1cT/WAw58z4txp1/QxM43ydDE/s=,tag:g0s6DQkRDIA1v/fywRN61A==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
